live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 1000

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command|Control"

[scrolling]
multiplier = 3

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "transparent"
dynamic_title = true
opacity = 0.8
startup_mode = "Fullscreen"
title = "Alacritty"

[window.dimensions]
columns = 180
lines = 49

[window.padding]
x = 7
y = 7
